In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pyarrow.dataset as ds

from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


In [2]:
cols = [
    'Airline','Origin','Dest','CRSDepTime',
    'Month','DayOfWeek','Distance','DistanceGroup',
    'DepDel15','DepDelayMinutes',
    'ArrDel15','ArrDelayMinutes','Cancelled','Diverted'
]

df = pd.read_parquet('./data/2021_delay_ds.parquet', columns=cols)

In [3]:
df.shape

(6311871, 14)

In [4]:
df.describe()

CRSDepTime         Month     DayOfWeek      Distance  DistanceGroup  \
count  6.311871e+06  6.311871e+06  6.311871e+06  6.311871e+06   6.311871e+06   
mean   1.323953e+03  6.969905e+00  4.013676e+00  7.955762e+02   3.653994e+00   
std    4.741972e+02  3.300914e+00  2.006264e+00  5.832931e+02   2.281563e+00   
min    1.000000e+00  1.000000e+00  1.000000e+00  3.100000e+01   1.000000e+00   
25%    9.200000e+02  4.000000e+00  2.000000e+00  3.700000e+02   2.000000e+00   
50%    1.315000e+03  7.000000e+00  4.000000e+00  6.460000e+02   3.000000e+00   
75%    1.723000e+03  1.000000e+01  6.000000e+00  1.033000e+03   5.000000e+00   
max    2.359000e+03  1.200000e+01  7.000000e+00  5.812000e+03   1.100000e+01   

           DepDel15  DepDelayMinutes      ArrDel15  ArrDelayMinutes  
count  6.203458e+06     6.203458e+06  6.185870e+06     6.185870e+06  
mean   1.731723e-01     1.276132e+01  1.726611e-01     1.252928e+01  
std    3.783962e-01     4.736319e+01  3.779540e-01     4.674770e+01  
min    0.000000e+00     0.000000e+00  0.000000e+00     0.000000e+00  
25%    0.000000e+00     0.000000e+00  0.000000e+00     0.000000e+00  
50%    0.000000e+00     0.000000e+00  0.000000e+00     0.000000e+00  
75%    0.000000e+00     6.000000e+00  0.000000e+00     6.000000e+00  
max    1.000000e+00     3.095000e+03  1.000000e+00     3.089000e+03

In [5]:
df.isnull().sum().sort_values(ascending=False)

ArrDel15           126001
ArrDelayMinutes    126001
DepDel15           108413
DepDelayMinutes    108413
Airline                 0
Origin                  0
DayOfWeek               0
Month                   0
CRSDepTime              0
Dest                    0
Distance                0
DistanceGroup           0
Cancelled               0
Diverted                0
dtype: int64

In [6]:
df[df.isnull().all(axis=1)]
all_nan_rows = df.isnull().all(axis=1).sum()
print(all_nan_rows)


0


In [7]:
df.isnull().sum().sort_values(ascending=False).head(20)

ArrDel15           126001
ArrDelayMinutes    126001
DepDel15           108413
DepDelayMinutes    108413
Airline                 0
Origin                  0
DayOfWeek               0
Month                   0
CRSDepTime              0
Dest                    0
Distance                0
DistanceGroup           0
Cancelled               0
Diverted                0
dtype: int64

In [8]:
df[['Cancelled','Diverted']].value_counts()

Cancelled  Diverted
False      False       6185871
True       False        111018
False      True          14982
Name: count, dtype: int64

# Tasks 
- 4 predictions 
    - Classification
        1. ArrivalDelay -> Binary classification 
            - Will the flight reach the destination late ?
        2. DepartureDelay -> Binary Classification
            - Will the flight take off late ? 
    - Regression
        1. ArrivalDelay
        2. DepartureDelay


## TASK 1 : DepartureDelay (Binary Classification)
### Does the flight takes off late ?

In [10]:
# Remove rows where the target departure delay 15 is missing (null) as label is missing 
df_departed = df[df['DepDel15'].notna()].copy()

df_departed.shape

(6203458, 14)

In [15]:
df_departed[df_departed['DepDel15']==1].shape

(1074267, 14)

In [16]:
df_departed[df_departed['DepDel15']!=1].shape

(5129191, 14)

#### Imbalanced Dataset 
Delayed (1):     1,074,267   (~17%)  
Not delayed (0): 5,129,191   (~83%)  
Total:           6,203,458


In [23]:
df_sample, _ = train_test_split(
    df_departed,
    train_size=200000,
    stratify=df_departed['DepDel15'],
    random_state=42
)

df_sample['DepDel15'].value_counts(normalize=True)

DepDel15
0.0    0.82683
1.0    0.17317
Name: proportion, dtype: float64

Feaure Engineering : Converted Hours, time to useful features

In [24]:
df_sample['DepHour'] = df_sample['CRSDepTime'] // 100

df_sample['DepHour_sin'] = np.sin(2 * np.pi * df_sample['DepHour'] / 24)
df_sample['DepHour_cos'] = np.cos(2 * np.pi * df_sample['DepHour'] / 24)

In [25]:
categorical_cols = [
    'Airline',
    'Origin',
    'Dest'
]

numeric_cols = [
    'Month',
    'DayOfWeek',
    'Distance',
    'DistanceGroup',
    'DepHour_sin',
    'DepHour_cos'
]

features = categorical_cols + numeric_cols

X = df_sample[features]
y = df_sample['DepDel15']


In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [27]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', 'passthrough', numeric_cols)
    ]
)

X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

In [32]:
# logistic_regression_model = LogisticRegression()
logistic_regression_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    n_jobs=-1,
)

In [33]:
logistic_regression_model.fit(X_train_encoded,y_train)

d:\Coding\ML\Projects\Flight Delay Prediction\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
d:\Coding\ML\Projects\Flight Delay Prediction\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1)

In [39]:
logistic_regression_model_pred = logistic_regression_model.predict(X_test_encoded)

In [40]:
print(classification_report(y_test, logistic_regression_model_pred))
print(confusion_matrix(y_test, logistic_regression_model_pred))
print("Accuracy:", accuracy_score(y_test, logistic_regression_model_pred))

              precision    recall  f1-score   support

         0.0       0.89      0.64      0.74     33073
         1.0       0.27      0.63      0.38      6927

    accuracy                           0.64     40000
   macro avg       0.58      0.63      0.56     40000
weighted avg       0.78      0.64      0.68     40000

[[21056 12017]
 [ 2554  4373]]
Accuracy: 0.635725


In [ ]:
'''
This is initial performance without class unbalanced and 100 iterations 
                   precision   recall    f1-score support
         0.0       0.83        1.00      0.91     33073
         1.0       0.63        0.01      0.01      6927

    accuracy                           0.83     40000
   macro avg       0.73      0.50      0.46     40000
weighted avg       0.79      0.83      0.75     40000

                    predicted 0     predicted 1
actual 0            [[33049         24]
actual 1            [ 6886          41]]
model has more false positives in 7k delayed flights it is predicting correctly only 41 VERY BAD
Accuracy: 0.82725


AFTER Class Baanced and 1000 iterations
                   precision    recall    f1-score   support
         0.0       0.89         0.64      0.74       33073
         1.0       0.27         0.63      0.38       6927

    accuracy                           0.64     40000
   macro avg       0.58      0.63      0.56     40000
weighted avg       0.78      0.64      0.68     40000

[[21056 12017]
 [ 2554  4373]]
Accuracy: 0.635725
'''

Random Forest

In [41]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    class_weight='balanced',
    n_jobs=-1,
    random_state=42
)

In [42]:
rf_model.fit(X_train_encoded, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=15, n_jobs=-1,
                       random_state=42)

In [43]:
rf_pred = rf_model.predict(X_test_encoded)

print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))
print("Accuracy:", accuracy_score(y_test, rf_pred))

              precision    recall  f1-score   support

         0.0       0.89      0.69      0.78     33073
         1.0       0.29      0.60      0.39      6927

    accuracy                           0.68     40000
   macro avg       0.59      0.64      0.59     40000
weighted avg       0.79      0.68      0.71     40000

[[22966 10107]
 [ 2804  4123]]
Accuracy: 0.677225


In [ ]:
''' 
Random Forest 
                  precision    recall    f1-score   support
         0.0       0.89        0.69      0.78       33073
         1.0       0.29        0.60      0.39       6927

    accuracy                           0.68     40000
   macro avg       0.59      0.64      0.59     40000
weighted avg       0.79      0.68      0.71     40000

[[22966 10107]
 [ 2804  4123]]
Accuracy: 0.677225







'''

XG Boost

In [46]:
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    n_jobs=-1,
    random_state=42,
    tree_method="hist"
)

In [47]:
xgb_model.fit(X_train_encoded, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=-1, num_parallel_tree=None, ...)

In [48]:
xgb_pred = xgb_model.predict(X_test_encoded)

print(classification_report(y_test, xgb_pred))
print(confusion_matrix(y_test, xgb_pred))
print("Accuracy:", accuracy_score(y_test, xgb_pred))

              precision    recall  f1-score   support

         0.0       0.90      0.70      0.79     33073
         1.0       0.30      0.62      0.41      6927

    accuracy                           0.69     40000
   macro avg       0.60      0.66      0.60     40000
weighted avg       0.79      0.69      0.72     40000

[[23179  9894]
 [ 2634  4293]]
Accuracy: 0.6868


In [52]:
'''
XG Boost initial run
                 precision   recall  f1-score   support
         0.0       0.90      0.70      0.79     33073
         1.0       0.30      0.62      0.41      6927

    accuracy                           0.69     40000
   macro avg       0.60      0.66      0.60     40000
weighted avg       0.79      0.69      0.72     40000

[[23179  9894]
 [ 2634  4293]]
Accuracy: 0.6868
'''

'\nXG Boost initial run\n                 precision   recall  f1-score   support\n         0.0       0.90      0.70      0.79     33073\n         1.0       0.30      0.62      0.41      6927\n\n    accuracy                           0.69     40000\n   macro avg       0.60      0.66      0.60     40000\nweighted avg       0.79      0.69      0.72     40000\n\n[[23179  9894]\n [ 2634  4293]]\nAccuracy: 0.6868\n'

Using RandomizedSearchCV to improve f1

In [50]:
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

xgb_base = XGBClassifier(
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    n_jobs=-1,
    random_state=42,
    tree_method="hist"
)

param_dist = {
    'n_estimators': [150, 200, 300],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1, 0.2],
    'min_child_weight': [1, 3, 5]
}


In [51]:
random_search = RandomizedSearchCV(
    xgb_base,
    param_distributions=param_dist,
    n_iter=10,
    scoring='f1',
    cv=3,
    verbose=1,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train_encoded, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


RandomizedSearchCV(cv=3,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=0.8, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_constraint...
                                           max_delta_step=None, max_depth=None,
                                           max_leaves=None,
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=-1,
                                           num_parallel_tree=None, ...),
                   n_jobs=-1,
                   param_distributions={'learning_rate': [0.05, 0.1, 0.2],
                                        'max_depth': [4, 6, 8],
                                        'min_child_weight': [1, 3, 5],
                                        'n_estimators': [150, 200, 300]},
                   random_state=42, scoring='f1', verbose=1)

In [53]:
print(random_search.best_params_)

{'n_estimators': 150, 'min_child_weight': 1, 'max_depth': 8, 'learning_rate': 0.05}


In [54]:
best_xgb = random_search.best_estimator_

pred = best_xgb.predict(X_test_encoded)

print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
print("Accuracy:", accuracy_score(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.90      0.71      0.79     33073
         1.0       0.31      0.62      0.41      6927

    accuracy                           0.69     40000
   macro avg       0.60      0.66      0.60     40000
weighted avg       0.80      0.69      0.73     40000

[[23419  9654]
 [ 2666  4261]]
Accuracy: 0.692


In [ ]:
''' 
Trying to optimize thersold
current (default) prob > 0.5 ----> class 1 (delayed)
'''

In [56]:
probs = best_xgb.predict_proba(X_test_encoded)[:, 1]